### ISSUE TITLE
CLASSIFIER-FREE DIFFUSION GUIDANCE

### ISSUE THREAD

**Issue by ZhZhuang** [LinXueyuanStdio/PyTorch-DDPM#3]
你好，非常感谢能够分享代码。和CLASSIFIER-FREE DIFFUSION GUIDANCE这篇论文的无分类器的方法是不同的吧。代码中是将标签编码直接放入模型中，这样做有理论依据吗？

**Comment by LinXueyuanStdio** [comment]
classifier-free 主要在于条件向量怎么和去噪模型交互，而不是条件向量怎么来。论文里的条件概率公式很清楚了。在这个仓库的具体实现是交叉注意力。

数字生成图片任务比较简单，我做了简化，直接用嵌入层生成条件向量了。当然，你可以采取其他方式生成条件变量，不一定用嵌入层，比如你可以用 BERT 支持自然语言生成条件向量。

**Comment by ZhZhuang** [comment]
谢谢大神的回答，我自身的基础比较薄弱
