### ISSUE TITLE
mean,variance

### ISSUE THREAD

**Issue by liuzysy** [LinXueyuanStdio/PyTorch-DDPM#4]
感谢您的代码分享，由于我个人基础薄弱，所以在前向过程和反向sample中的代码并未看懂，因为我发现和主流视频包括论文里的算法的公式不一样，所以我想请问您使用的公式是怎么计算得出的。

**Comment by LinXueyuanStdio** [comment]
按照论文的公式来的啊。。。感觉你没梳理过公式，建议看这篇文章入门 https://kexue.fm/archives/9119

我梳理后的公式在这： https://timecat.notion.site/DDPM-b8e2a91927d249fdbcf7c82f2eb6f846
